### PR TITLE
added combyne template engine

### PR DESCRIPTION
**Pull request by tbranyen**
to list

### CODE REVIEW

**Comment by paularmstrong** [comment]
I don't see the lib file or simple.html template included for benchmarking.

Can you make sure to add those as well?

**Comment by tbranyen** [comment]
The typical hunk I am, totally forgot git add... incoming git -f...

**Comment by tbranyen** [comment]
Hey @paularmstrong updated the README as well.  Hope I didn't miss anything else.

**Comment by paularmstrong** [comment]
After merging, I'm finding that the templates aren't built correctly. I'm reverting this out. I'm not really sure how to fix it, as I'm not familiar with Combyne. Would you be able to clear this up?

This is the output that I see:

```
<h1>Colors</h1>
<ul>
    <li><a href=""></a></li>
</ul>
```

But I'm expecting to see:

```
<h1>Colors</h1>
<ul>
     <li><strong>red</strong></li>
     <li><a href="#Green">green</a></li>
     <li><a href="#Blue">blue</a></li>
</ul>
```

**Comment by tbranyen** [comment]
Investigating right now.

**Pull request merged**
