### PR TITLE
Added Blade template engine

### PR DESCRIPTION
**Pull request by bminer**

### CODE REVIEW

**Comment by daslicht** [comment]
Can we see the results somewhere ?

**Comment by bminer** [comment]
I presume that results will be posted once @paularmstrong goes through some of this stuff?

I can tell you that Blade is pretty darn slow when it comes to compiling... almost the worst on the list.  :)  I've seen it run at about 250 - 300 small templates per second.  That's not all that good...

Sadly, the benchmark tool doesn't output the rendering results for you -- as far as I know.  If you want, you can clone my fork of `node-templates` and check it out.  I couldn't figure it out, but I didn't spend much time on it, honestly.

As I mentioned before, Blade's rendering performance should be pretty decent.  It's pretty typical to get around 1000 or 2000 renders per second -- much faster than your eye can detect changes on the screen.

Also, please feel free to checkout this link: https://github.com/bminer/node-blade/wiki/Benchmarks

**Comment by daslicht** [comment]
Thank You !

**Comment by bminer** [comment]
@paularmstrong - Any chance of merging this?

**Comment by daslicht** [comment]
:+1:

**Pull request closed without merging**
